[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
name = 'pallet-template'
version = "3.0.0"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = [
	"derive",
] }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/system" }
frame-benchmarking = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/benchmarking", optional = true }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-std = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/std" }
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }
sp-keystore = { version = "0.10.0-dev", path = "../../../../primitives/keystore", optional = true }
log = { version = "0.4.14", default-features = false }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-io/std',
	'sp-std/std',
	'sp-keystore/std',
	'log/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
